# Site settings
title: "Patrick's Irish Pub"
email: "team@variantstudios.com"
description: "Patrick's Irish Pub - Greeley, Colorado"
baseurl: "" # the subpath of your site, e.g. /blog/ - keep empty!
url: "http://www.patricksgreeley.com" # the base hostname & protocol for your site - don't include the forward slash
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.2.1" # the version of jekyll

#CloudCannon defaults
uploads_dir: "assets/images"

# Gems for plugins
gems:
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Cloudinary URL - something like: https://res.cloudinary.com/domain-com/
cloudinaryurl:

# typekit - Because we all need nice type faces.
typekit:

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id: "UA-48511474-1"

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]

published: false